### ISSUE TITLE
Number of Iterations is off by 1

### ISSUE THREAD

**Issue by jtykal** [RallyCommunity/rally-iteration-health#3]
Selecting a "Number of Iterations" in the app results in ONE FEWER iterations than the number selected to be displayed. (For example, if I choose "5" in Number of Iterations, it displays data for 4 iterations.)

**Comment by krmorse** [comment]
You're totally right- Just repro'ed.  Looking into a fix...

**Comment by krmorse** [comment]
@jtykal i think i fixed it.  mind copy/pasting this into a custom html app to test the fix?

https://raw.githubusercontent.com/RallyCommunity/rally-iteration-health/dd912f89a0bc73e2196e309b383241ffce8e7773/deploy/App.txt

if you're good w/ it i'll merge it and get it incorporated back into the community app catalog in the product.

**Comment by jtykal** [comment]
Looks good, Kyle!  Thanks for the quick turnaround...

*Jim Tykal*
jim@tykal.net
